services:
  service-1:
    container_name: service-1
    image: hashicorp/http-echo:latest
    networks:
      - envoy-network
    environment:
      - ECHO_TEXT="hello world! service-1"
  service-2:
    container_name: service-2
    image: hashicorp/http-echo:latest
    networks:
      - envoy-network
    environment:
      - ECHO_TEXT="hello world! service-2"
  envoy:
    image: envoyproxy/envoy:tools-v1.35-latest
    ports:
      - 9901:9901
      - 10000:10000
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    command: ["envoy", "-c", "/etc/envoy/envoy.yaml"]
    depends_on:
      - service-1
      - service-2
    networks:
      - envoy-network

networks:
  envoy-network:
    driver: bridge